// AUTOGENERATED FILE
// This file was generated from webidl.ohm by `ohm generateBundles`.

import {
  BaseActionDict,
  Grammar,
  IterationNode,
  Node,
  NonterminalNode,
  Semantics,
  TerminalNode
} from 'ohm-js';

export interface WebIDLActionDict<T> extends BaseActionDict<T> {
  Definitions?: (this: NonterminalNode, arg0: IterationNode) => T;
  Definition?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Interface?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: IterationNode, arg3: TerminalNode, arg4: NonterminalNode, arg5: TerminalNode, arg6: TerminalNode) => T;
  InterfaceMembers?: (this: NonterminalNode, arg0: IterationNode) => T;
  InterfaceMember?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Attribute?: (this: NonterminalNode, arg0: IterationNode, arg1: TerminalNode, arg2: NonterminalNode, arg3: NonterminalNode, arg4: TerminalNode) => T;
  Operation?: (this: NonterminalNode, arg0: IterationNode, arg1: NonterminalNode, arg2: NonterminalNode, arg3: TerminalNode, arg4: IterationNode, arg5: TerminalNode, arg6: TerminalNode) => T;
  Constructor?: (this: NonterminalNode, arg0: TerminalNode, arg1: TerminalNode, arg2: IterationNode, arg3: TerminalNode, arg4: TerminalNode) => T;
  Type?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  SingleType?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  PrimitiveType?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode | TerminalNode) => T;
  UnionType?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: NonterminalNode, arg4: IterationNode, arg5: IterationNode, arg6: TerminalNode) => T;
  SequenceType?: (this: NonterminalNode, arg0: TerminalNode, arg1: TerminalNode, arg2: NonterminalNode, arg3: TerminalNode) => T;
  FrozenArrayType?: (this: NonterminalNode, arg0: TerminalNode, arg1: TerminalNode, arg2: NonterminalNode, arg3: TerminalNode) => T;
  Inheritance?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  ArgumentList?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode, arg2: IterationNode) => T;
  Argument?: (this: NonterminalNode, arg0: IterationNode, arg1: NonterminalNode, arg2: NonterminalNode, arg3: IterationNode, arg4: IterationNode) => T;
  DefaultValue?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Partial?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  Namespace?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: NonterminalNode, arg4: TerminalNode, arg5: TerminalNode) => T;
  Dictionary?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: IterationNode, arg3: TerminalNode, arg4: NonterminalNode, arg5: TerminalNode, arg6: TerminalNode) => T;
  NamespaceMembers?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  DictionaryMember?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode, arg2: TerminalNode) => T;
  Enum?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: NonterminalNode, arg4: TerminalNode, arg5: TerminalNode) => T;
  EnumValues?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Typedef?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: NonterminalNode, arg3: TerminalNode) => T;
  Stringifier?: (this: NonterminalNode, arg0: TerminalNode, arg1: TerminalNode) => T;
  ident?: (this: NonterminalNode, arg0: IterationNode, arg1: IterationNode) => T;
  num?: (this: NonterminalNode, arg0: IterationNode) => T;
  str?: (this: NonterminalNode, arg0: TerminalNode, arg1: TerminalNode, arg2: TerminalNode) => T;
}

export interface WebIDLSemantics extends Semantics {
  addOperation<T>(name: string, actionDict: WebIDLActionDict<T>): this;
  extendOperation<T>(name: string, actionDict: WebIDLActionDict<T>): this;
  addAttribute<T>(name: string, actionDict: WebIDLActionDict<T>): this;
  extendAttribute<T>(name: string, actionDict: WebIDLActionDict<T>): this;
}

export interface WebIDLGrammar extends Grammar {
  createSemantics(): WebIDLSemantics;
  extendSemantics(superSemantics: WebIDLSemantics): WebIDLSemantics;
}

declare const grammar: WebIDLGrammar;
export default grammar;

